/* Generated by Yosys 0.65+51 (git sha1 5c6de0446-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* cells_not_processed =  1  *)
(* src = "adder.v:1.1-7.10" *)
module full_adder(A, B, Cin, Sum, Cout);
  (* src = "adder.v:2.7-2.8" *)
  input A;
  wire A;
  (* src = "adder.v:2.10-2.11" *)
  input B;
  wire B;
  (* src = "adder.v:2.13-2.16" *)
  input Cin;
  wire Cin;
  (* src = "adder.v:3.8-3.11" *)
  output Sum;
  wire Sum;
  (* src = "adder.v:3.13-3.17" *)
  output Cout;
  wire Cout;
  (* src = "adder.v:6.16-6.21" *)
  wire _0_;
  (* src = "adder.v:6.26-6.39" *)
  wire _1_;
  (* src = "adder.v:5.14-5.19" *)
  wire _2_;
  assign _0_ = A & (* src = "adder.v:6.16-6.21" *) B;
  assign _1_ = _2_ & (* src = "adder.v:6.26-6.39" *) Cin;
  assign Cout = _0_ | (* src = "adder.v:6.15-6.40" *) _1_;
  assign Sum = _2_ ^ (* src = "adder.v:5.14-5.25" *) Cin;
  assign _2_ = A ^ (* src = "adder.v:6.27-6.32" *) B;
endmodule
